### ISSUE TITLE
[Docs] `mermaid.js` diagram rendering issue in Move Reference Documentation

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/developer-docs#40]
# Aptos Documentation Issue

## Location
https://aptos.dev/reference/move/?branch=mainnet&page=aptos-framework/doc/storage_gas.md#function-dependencies

## Description
`mermaid.js` diagrams are not rendered properly at the Move Reference Documentation in `aptos.dev`
<img width="1009" alt="image" src="https://github.com/aptos-labs/developer-docs/assets/7842757/4e6c85f9-0d19-4214-8252-c5e08301dfa0">

They are rendered well in github.

https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/doc/storage_gas.md#function-dependencies

<img width="922" alt="image" src="https://github.com/aptos-labs/developer-docs/assets/7842757/435c0200-721d-4496-ac05-0d2803e9845b">

**Comment by gregnazario** [comment]
@junkil-park this may be fixed, can you followup?

**Comment by junkil-park** [comment]
<img width="775" alt="image" src="https://github.com/aptos-labs/developer-docs/assets/7842757/0cabf8b6-2e7a-41bc-8b34-ca29983365b3">

Thank you, @gregnazario , Yes, it's fixed!

One thing is that: I found that the lines were not very visible in the dark mode. I am wondering if it can use the dark theme in the dark mode? https://mermaid.js.org/config/theming.html#available-themes

**Comment by gregnazario** [comment]
> <img alt="image" width="775" src="https://private-user-images.githubusercontent.com/7842757/298211797-0cabf8b6-2e7a-41bc-8b34-ca29983365b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDM3ODQsIm5iZiI6MTcwNTcwMzQ4NCwicGF0aCI6Ii83ODQyNzU3LzI5ODIxMTc5Ny0wY2FiZjhiNi0yZTdhLTQxYmMtOGIzNC1jYTI5OTgzMzY1YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMjIzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJhYjczYmZlYzc1Y2VmMmNiZmJjMTVlNDFjYWU1ZjZjZDg0MzE2N2JjZDJlMDY3OTRjYjUyY2VmMWY2ZGQ5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8AQBF-9UDB0D7XvUVawQS3J3-Eqo3OtVrjigkB1dS90">
> Thank you, @gregnazario , Yes, it's fixed!
> 
> One thing is that: I found that the lines were not very visible in the dark mode. I am wondering if it can use the dark theme when it is in the dark mode? https://mermaid.js.org/config/theming.html#available-themes

Looks like defaulting to dark mode is an option for now https://github.com/aptos-labs/developer-docs/pull/100

@moonclavedev can follow up with being able to switch with the website, but I'm not an expert in that space

**Comment by gregnazario** [comment]
This should be good enough for now.
