### ISSUE TITLE
[Docs] Install-cli-windows

### ISSUE THREAD

**Issue by phapdev** [aptos-labs/developer-docs#487]
# Aptos Documentation Issue

## Location
URL:  https://aptos.dev/en/build/cli/install-cli/install-cli-windows

## Description

When installing you have a document: ``` setx PATH "%PATH%;C:\Users\<your_account_name>\.aptoscli\bin"```
⚠️ When I run that command, all my PATHs are deleted and replaced with exactly 1 of your PATHs, this gives me an error, for example the development environments like python, nodejs I installed before cannot work. 

![image](https://github.com/aptos-labs/developer-docs/assets/101971044/cdaed999-9f4c-47f2-a384-8c57f649758a)

🤔 There should be a warning  for this ⚠️, or instructions for setting the PATH for the environment on windows.

After running the command
![image](https://github.com/aptos-labs/developer-docs/assets/101971044/31679983-2d7b-4d6e-a22b-662c6d5198ea)

**Comment by igor-p** [comment]
@phapdev We recently pushed https://github.com/aptos-labs/developer-docs/pull/609 to fix the Windows CLI issue. Can you try again with the updated instructions and let me know if it still fails?

**Comment by igor-p** [comment]
Closing as fixed
