### ISSUE TITLE
[Docs] Fix Broken Links

### ISSUE THREAD

**Issue by Tlazypanda** [aptos-labs/developer-docs#522]
# Aptos Documentation Issue

A wide search across the developer docs website shows 357 broken links. A lot of these are GitHub broken links due to repositories moving to another location. 

The project readme mentions lychee link checker for the incoming PRs so we can focus on clearing the backlog broken links. The link checker shows 230 broken links vs online checkers showing >350 so might have to investigate on what is not considered to be broken in case of our workflow. 

## Location
The complete report of failing URLs is attached.
[Uploading Dead Link Checker report - http:www.aptos.dev.pdf…]()

**Comment by hariria** [comment]
It seems like you're missing a link. The link appears to be empty, could you update it?
