### ISSUE TITLE
[Docs] Wrong links on network/nodes/validator-node/deploy-nodes

### ISSUE THREAD

**Issue by alex4506** [aptos-labs/developer-docs#523]
# Aptos Documentation Issue

## Location

https://aptos.dev/en/network/nodes/validator-node/deploy-nodes

## Description

Some links in this page are wrong ( should point to `validator-node` not `full-node`
* Using Source Code
* Using Docker
* Using GCP

**Comment by michelle-aptos** [comment]
this is fixed now!
