### ISSUE TITLE
[Docs] Upgrade via VFN Failover document does not mention the need to rename the docker volume

### ISSUE THREAD

**Issue by alex4506** [aptos-labs/developer-docs#524]
# Aptos Documentation Issue

## Location

https://aptos.dev/en/network/nodes/validator-node/modify-nodes/update-validator-node#upgrade-via-vfn-failover

## Description

When using docker compose, VFN and Validator using different docker volume path. 
We must first rename the volume name; otherwise, compose will fail to start.

**Comment by sionescu** [comment]
@alex4506 can you point me to where the paths are specified as different ?

**Comment by alex4506** [comment]
@sionescu For validators, they use `aptos-validator` as volume path, for VNF, they use `aptos-fullnode`

**Comment by igor-p** [comment]
> @sionescu For validators, they use `aptos-validator` as volume path, for VNF, they use `aptos-fullnode`

Hi @alex4506, can you provide a URL of where you are seeing this?

**Comment by alex4506** [comment]
@igor-p https://aptos.dev/en/network/nodes/configure/node-files-all-networks/node-files-mainnet  , please check the `docker-compose.yaml` & `docker-compose-fullnode.yaml`
