### ISSUE TITLE
Add identifiers for certain optional advanced features

### ISSUE THREAD

**Issue by WGB5445** [aptos-labs/developer-docs#562]
### Url

https://aptos.dev/en/build/get-started/developer-setup

### Describe the content issue

I’ve received feedback from several developers. They found the path for installing the Aptos CLI based on the documentation, but encountered issues when trying to follow the steps to set up Prove:

The setup process for Prove involves too many steps.
Some libraries are missing during the setup of Prove.
But the most important issue is that Prove should be optional. Most beginners don’t know what Prove does and don’t need to install it in the first step.

Therefore, we should add an “Optional/Advanced Feature” label for Prove to indicate that this feature is not necessary.

<img width="870" alt="image" src="https://github.com/user-attachments/assets/972d96eb-7c06-4485-8e18-3fb73c6ed1c2">

### Section

cli

**Comment by igor-p** [comment]
@WGB5445's [PR](https://github.com/aptos-labs/developer-docs/pull/563) seems to address the issue. If the tag isn't clear enough for people, we can add it as a pill or add a callout on the page.
