### ISSUE TITLE
[Docs] Search

### ISSUE THREAD

**Issue by hariria** [aptos-labs/developer-docs#580]
# Aptos Documentation Issue

## Description

Some folks internally have voiced concerns around the search functionality on aptos.dev, especially using the search to find specific content. Some have also mentioned that the search glitches in some instances (based on my experience, this is because the indices on aptos.dev are so large and they’re all held client-side, UI glitches as its loading indices based on search query). 

## Additional context

Internal tracking doc: https://www.notion.so/aptoslabs/Search-on-aptos-dev-587638526eef491d8c5b99000ed05107?pvs=4

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
