### ISSUE TITLE
The level of the article directory is incorrect

### ISSUE THREAD

**Issue by narnona** [aptos-labs/developer-docs#602]
### Url

https://aptos.dev/en/build/smart-contracts/objects/creating-objects

### Describe the content issue

"Allowing Deletion of an Object" should be at the same level as "One Time Transfers".
![20240914143337](https://github.com/user-attachments/assets/b1da7d7f-612f-4389-99cb-0da4c82d63fd)

### Section

move-and-smart-contracts

**Comment by igor-p** [comment]
There seems to be a formatting problem (which is affecting the table of contents in the sidebar). I can take a look.
