### ISSUE TITLE
Smart Contracts Get Started

### ISSUE THREAD

**Issue by MattWong-ca** [aptos-labs/developer-docs#612]
### Url

https://aptos.dev/en/build/smart-contracts/compiling

### Describe the content issue

I'm new to Aptos and was a little confused by what the module name was:

In [Compiling](https://aptos.dev/en/build/smart-contracts/compiling), it says that `<MODULE_NAME>` is what I should see in the Terminal output, but in [Deployment](https://aptos.dev/en/build/smart-contracts/deployment), it uses `<your_module_name>` for the command.

I think it'd be more clear if `<your_module_name>` is replaced with `<named_address>` in [Deployment](https://aptos.dev/en/build/smart-contracts/deployment). Specifying this in `module hello_blockchain::message {}` earlier on in [Create Package](https://aptos.dev/en/build/smart-contracts/create-package) might also help! 

Compiling:
<img width="480" alt="Screenshot 2024-09-19 at 3 36 01 PM" src="https://github.com/user-attachments/assets/060e7d1a-207d-45bd-95a9-6f6d62d39ad3">

Deployment:
<img width="645" alt="Screenshot 2024-09-19 at 3 36 25 PM" src="https://github.com/user-attachments/assets/48466747-e12d-41b0-a737-5e2de26bcae1">

### Section

move-and-smart-contracts

**Comment by gregnazario** [comment]
Thanks for the suggestions, I've incorporated them ehre https://github.com/aptos-labs/developer-docs/pull/648
