### ISSUE TITLE
Randomness documentation needs an update 

### ISSUE THREAD

**Issue by lopeselio** [aptos-labs/developer-docs#623]
### Url

https://aptos.dev/en/build/smart-contracts/randomness

### Describe the content issue

[Aptos Randomness Docs](https://aptos.dev/en/build/smart-contracts/randomness) points out that Aptos Random Roll is live on Aptos Testnet and Devnet but a tweet from the foundation and an email said it was live on [mainnet](https://x.com/Aptos/status/1804553715468435654)

### Section

move-and-smart-contracts, apis

**Comment by hariria** [comment]
cc @alinush

**Comment by alinush** [comment]
Fixed [here](https://github.com/aptos-labs/developer-docs/pull/654).
