### ISSUE TITLE
Does aptos provide hardware wallet ledger suppport using typescript SDK ?

### ISSUE THREAD

**Issue by supra-bhavisha** [aptos-labs/developer-docs#624]
### Url

https://aptos.dev/en/build/cli/trying-things-on-chain/ledger

### Describe the content issue

I found CLI support for ledger. I need sdk typescript code to use hardware ledger

### Section

sdks, cli

**Comment by Hongquanbkct** [comment]
Please help me
I can't withdraw apt to my wallet after unstacking successfully
![z5838812238266_17fa3adbaa483d9df21a10f712f0a362](https://github.com/user-attachments/assets/1d86e094-9661-47b1-b198-c329d3dcf8fb)

![Uploading z5931042770804_ae44c8c57253e3c9705f94b9553abac4.jpg…]()
