### ISSUE TITLE
[Docs] Link broken

### ISSUE THREAD

**Issue by fEst1ck** [aptos-labs/developer-docs#675]
There are two broken links in the documentation

https://github.com/aptos-labs/developer-docs/blob/f7d6b8c1be2975ef8a37252df206756b11679044/apps/nextra/pages/en/network/blockchain/governance.mdx?plain=1#L45

https://github.com/aptos-labs/developer-docs/blob/f7d6b8c1be2975ef8a37252df206756b11679044/apps/nextra/pages/en/network/blockchain/governance.mdx?plain=1#L47

**Comment by jmintuitive** [comment]
Thanks for posting this :) - I'll go fix those links now.
